[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libpq-dev postgresql-client nodejs npm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
    "npm cache clean --force || true",
    "rm -rf node_modules package-lock.json || true",
    "npm install --no-optional --legacy-peer-deps || echo 'NPM install failed, continuing...'",
    "npm run build || echo 'NPM build failed, continuing...'",
    "php artisan config:cache || echo 'Config cache failed, continuing...'",
    "php artisan route:cache || echo 'Route cache failed, continuing...'",
    "php artisan view:cache || echo 'View cache failed, continuing...'"
]
