[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libpq-dev postgresql-client nodejs npm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
    "npm cache clean --force || true",
    "rm -rf node_modules package-lock.json || true",
    "npm install --no-optional --legacy-peer-deps",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
