[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libpq-dev postgresql-client nodejs npm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
